### ISSUE TITLE
Enable ROOT input

### ISSUE THREAD

**Issue by nietootein** [ctlearn-project/ctlearn#96] opened 2019-03-21 14:10 UTC
So far, CTLearn takes data in [HDF5](https://www.hdfgroup.org/solutions/hdf5/) format as input. However, most of the data from IACTs currently in operation come in [ROOT](https://root.cern.ch/) format. Enabling ROOT input in CTLearn will open its doors to existing IACT facilities.

An interesting ROOT I/O solution implemented using python and numpy (i.e. no need to use ROOT itself) is the [uproot](https://github.com/scikit-hep/uproot) package, part of the [Scikit-HEP](https://github.com/scikit-hep) project.

**Comment by johnkimdinh** [comment] 2019-03-21 17:24
Hi, you can follow here an example of converting MAGIC (existing IACT) from root to HDF5: https://github.com/cta-observatory/cta-lstchain/tree/master/lstchain/magic-lst

It was done using pyroot (IMHO less elegant than uproot) but there are plans to rewrite code using uproot.

**Comment by nicolamarinello** [comment] 2019-03-21 18:39
Hi all, I'm a master student at the University of Padova doing my last year on Telecommunications Engineering. I've been working on my master thesis on LST images analysis with CNNs for event reconstruction. So far I've used the DL1_ML1 machine learning dataset in HDF5 file format available in the [CTA internal wiki](https://forge.in2p3.fr/projects/machine-learning-for-event-reconstruction/wiki) and then it would be really nice working on this project to enable CTLearn natively loading data from currently working IACTs!

**Comment by nietootein** [comment] 2019-03-22 09:51
Thanks for the pointer, @johnkimdinh! Ideally, we'd like to avoid adding pyroot as a dependency and implement this new feature by means of uproot instead. Good to know that there are plans to rewrite what's already in place using uproot!

Ciao, @nicolamarinello! Happy to hear that you'd be interested in contributing to this project, moreover if you have previous experience with CTA data and with CNNs. We are currently planning on enabling this feature on CTLearn through [DL1-data-handler](https://github.com/cta-observatory/dl1-data-handler), a package of utilities for writing, reading, and applying image processing to IACT data. The implementation of the DL1-data-handler reader (it reads from hdf5 files previously produced by the writer) is currently under a [PR](https://github.com/cta-observatory/dl1-data-handler/pull/36), so having a look into the DL1-data-handler package and the mentioned PR could be a good starting point.

**Comment by nicolamarinello** [comment] 2019-03-25 18:34
Ciao @nietootein, thank you for the tips! 
I've been looking for a while the repos structure. I see that a reader is currently implemented in CTLearn. What you should make clear is: do you want to get rid of the reader currently implemented  in CTLearn integrating DL1-data-handler and make the latter able to manage also ROOT files, either you want to implement a ROOT reader inside CTLearn? I would go for the first as it is more elegant and also other repos can benefit from it.

**Comment by aribrill** [comment] 2019-03-25 20:03
Hi @nicolamarinello, yes, the former approach is exactly what we'd like to do, for both of the reasons you state.

**Comment by nicolamarinello** [comment] 2019-03-26 16:23
Could this be a problem in the application process? As probably most of the final code will be merged into the repo DL1-data-handler and a smaller part in CTLearn.

**Comment by aribrill** [comment] 2019-03-26 20:07
DL1DataHandler is associated with CTLearn (the core development team is a collaboration between CTLearn and a similar project using PyTorch, [GammaLearn](https://gitlab.lapp.in2p3.fr/GammaLearn/GammaLearn)), so as far as we're concerned at least, that the code would go in DL1DH is all the same for the project/application process.

**Comment by lightningedge007a** [comment] 2019-04-05 20:07
Hi @aribrill , I am 3rd year, Computer Science, Bachelor of Technology student from Jaypee Institute of Information Technology. I found ROOT Input and Regression projects to be amazing and I want to pick them up for GSOC 2019. Can you please guide me on which one should I draft my proposal according to my skillset:
**SKILLS**
Machine Learning, Deep Learning, Artificial Intelligence, Data Analysis, Data Science,Natural Language Processing (NLP), Artificial Intelligence (AI),
Computer Vision, PyTorch, Keras, TensorFlow,
Python, Java, C/C++
Docker, Git, Google Colab, Amazon Web Services (AWS), Cloud Computing
PL/SQL, Object-Oriented Programming (OOP), Linux

**Comment by lightningedge007a** [comment] 2019-04-06 12:16
Hi @aribrill @nietootein @qi-feng , I am currently making a proposal on ROOT Input project, how can I contact the mentors for feedback, etc. Any help? And regarding PR, what shall it solve? There weren't any issues on this project in ideas page https://openastronomy.org/gsoc/gsoc2019/#/projects?project=root_input

**Comment by lightningedge007a** [comment] 2019-04-07 06:42
> So far, CTLearn takes data in [HDF5](https://www.hdfgroup.org/solutions/hdf5/) format as input. However, most of the data from IACTs currently in operation come in [ROOT](https://root.cern.ch/) format. Enabling ROOT input in CTLearn will open its doors to existing IACT facilities.
> 
> An interesting ROOT I/O solution implemented using python and numpy (i.e. no need to use ROOT itself) is the [uproot](https://github.com/scikit-hep/uproot) package, part of the [Scikit-HEP](https://github.com/scikit-hep) project.

@nietootein I tried to approach the problem this way: 
ROOT -> uproot -> numpy -> h5py -> save to hdf5 format.
I also explored pyroot but understood your reluctance to use it because it is dependent on C++ whereas uproot uses pyhton's numpy and is faster too!

**Comment by VanshikaMittal07** [comment] 2019-04-07 10:57
Hi @aribrill , I am currently in 3rd year, Computer Science, Bachelor of Technology student from JIIT. I find Regression and classification problems amazing. I am interested in exploring more about ctlearn and how it classifies and currently i am working on converting root input data to hdf5 format.

**Comment by TjarkMiener** [comment] 2022-07-11 12:47
[DL1DH](https://github.com/cta-observatory/dl1-data-handler) and [ctapipe-io-magic](https://github.com/cta-observatory/ctapipe_io_magic) support the translation of MAGIC simulation and data files from ROOT to hdf5. Similar efforts are on the way for the other IACTs. Reading directly from the ROOT files into CTLearn is currently not a feature that we would like to support in CTLearn. I'm closing this issue.

**Closed by TjarkMiener** 2022-07-11 12:47 UTC
Labels: enhancement, help wanted
